/*
  inject-hashes.js
  Rewrites HTML to point to actual hashed files in dist/ generated by esbuild on Netlify.
  Safe to run locally and in CI.
*/

const fs = require("fs");
const path = require("path");

function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function buildMap(dir, ext) {
  const abs = path.resolve(dir);
  if (!fs.existsSync(abs)) return {};
  const files = fs.readdirSync(abs);
  const map = {};
  for (const file of files) {
    if (!file.endsWith(ext)) continue;
    const m = file.match(/^(.*)-([A-Za-z0-9]{6,})\.(css|js)$/);
    if (!m) continue;
    const base = m[1];
    map[base] = file;
  }
  return map;
}

function replacePaths(content, type, map) {
  const exts = type === "css" ? "css" : "js";
  for (const [base, filename] of Object.entries(map)) {
    const pat1 = new RegExp(`\\.\\/dist\\/${type}\\/${escapeRegExp(base)}-[A-Za-z0-9]+\\.${exts}`, "g");
    const pat2 = new RegExp(`\\/dist\\/${type}\\/${escapeRegExp(base)}-[A-Za-z0-9]+\\.${exts}`, "g");
    const pat3 = new RegExp(`dist\\/${type}\\/${escapeRegExp(base)}-[A-Za-z0-9]+\\.${exts}`, "g");
    content = content.replace(pat1, `./dist/${type}/${filename}`);
    content = content.replace(pat2, `/dist/${type}/${filename}`);
    content = content.replace(pat3, `dist/${type}/${filename}`);
  }
  return content;
}

function processHtmlFile(filePath, cssMap, jsMap) {
  const abs = path.resolve(filePath);
  if (!fs.existsSync(abs)) return false;
  let before = fs.readFileSync(abs, "utf8");
  let after = replacePaths(before, "css", cssMap);
  after = replacePaths(after, "js", jsMap);
  if (after !== before) {
    fs.writeFileSync(abs, after, "utf8");
    return true;
  }
  return false;
}

function collectHtmlFiles() {
  const out = [];
  const roots = ["index.html"];
  for (const f of roots) { if (fs.existsSync(f)) out.push(f); }
  const pagesDir = path.resolve("pages");
  if (fs.existsSync(pagesDir)) {
    for (const f of fs.readdirSync(pagesDir)) {
      if (f.endsWith(".html")) out.push(path.join("pages", f));
    }
  }
  return out;
}

function run() {
  const cssMap = buildMap("dist/css", ".css");
  const jsMap = buildMap("dist/js", ".js");
  const files = collectHtmlFiles();
  let changed = 0;
  for (const f of files) {
    if (processHtmlFile(f, cssMap, jsMap)) changed++;
  }
  const report = {
    css: Object.keys(cssMap).length,
    js: Object.keys(jsMap).length,
    htmlChanged: changed
  };
  console.log("[inject-hashes]", JSON.stringify(report));
}

run();