name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci || npm i

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm test -- --run

      - name: Build
        run: npm run build

      # Placeholders for audits aligned with repo rules.
      # Replace with your project-specific commands when available.
      - name: Accessibility audit (placeholder)
        run: echo "Run pa11y-ci or axe-core here"

      - name: Performance/SEO audit (placeholder)
        run: echo "Run Lighthouse and link-check here"